# This file was generated by the {rix} R package v0.4.1 on 2023-11-21
# with following call:
# >rix(r_ver = "976fa3369d722e76f37c77493d99829540d43845",
#  > r_pkgs = c("quarto",
#  > "dplyr",
#  > "DT",
#  > "flexdashboard",
#  > "forcats",
#  > "formattable",
#  > "ggplot2",
#  > "ggVennDiagram",
#  > "grid",
#  > "gridExtra",
#  > "here",
#  > "knitr",
#  > "networkD3",
#  > "optparse",
#  > "plotly",
#  > "qs",
#  > "quarto",
#  > "rmarkdown",
#  > "stringr",
#  > "targets",
#  > "this.path",
#  > "treemap",
#  > "vegan",
#  > "viridis",
#  > "visNetwork"),
#  > system_pkgs = "quarto",
#  > tex_pkgs = c("amsmath",
#  > "framed",
#  > "fvextra",
#  > "environ",
#  > "fontawesome5",
#  > "orcidlink",
#  > "pdfcol",
#  > "tcolorbox",
#  > "tikzfill"),
#  > ide = "rstudio",
#  >      project_path = ".",
#  > overwrite = TRUE,
#  > print = TRUE,
#  > shell_hook = "")
# It uses nixpkgs' revision 976fa3369d722e76f37c77493d99829540d43845 for reproducibility purposes
# which will install R version 4.3.1
# Report any issues to https://github.com/b-rodrigues/rix
let
 pkgs = import (fetchTarball "https://github.com/NixOS/nixpkgs/archive/976fa3369d722e76f37c77493d99829540d43845.tar.gz") {};
 rpkgs = builtins.attrValues {
  inherit (pkgs.rPackages) quarto dplyr DT flexdashboard forcats formattable ggplot2 ggVennDiagram grid gridExtra here knitr networkD3 optparse plotly qs quarto rmarkdown stringr targets this_path treemap vegan viridis visNetwork;
};
  tex = (pkgs.texlive.combine {
  inherit (pkgs.texlive) scheme-small amsmath framed fvextra environ fontawesome5 orcidlink pdfcol tcolorbox tikzfill;
});
 system_packages = builtins.attrValues {
  inherit (pkgs) R glibcLocalesUtf8 quarto;
};
 rstudio_pkgs = pkgs.rstudioWrapper.override {
  packages = [  rpkgs ];
};
 in
  pkgs.mkShell {
    LOCALE_ARCHIVE = if pkgs.system == "x86_64-linux" then  "${pkgs.glibcLocalesUtf8}/lib/locale/locale-archive" else "";
    LANG = "en_US.UTF-8";
    LC_ALL = "en_US.UTF-8";
    LC_TIME = "en_US.UTF-8";
    LC_MONETARY = "en_US.UTF-8";
    LC_PAPER = "en_US.UTF-8";
    LC_MEASUREMENT = "en_US.UTF-8";

    buildInputs = [  rpkgs tex system_packages rstudio_pkgs ];
      
  }
