---
title: "Reclustering"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Reclustering}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup, message=FALSE}
library(MiscMetabar)
```

# Re-clustering ASVs

## Using decipher or Vsearch algorithm
```{r}
data(data_fungi_sp_known)
otu <- asv2otu(data_fungi_sp_known, method = "clusterize")
```

```{r, eval = FALSE}
otu_vs <- asv2otu(data_fungi_sp_known, method = "vsearch")
```

The vsearch method requires the installation of [Vsearch](https://github.com/torognes/vsearch).

```{r}
summary_plot_pq(data_fungi_sp_known)
summary_plot_pq(otu)
```

## Using lulu algorithm [link to LULU article](https://www.nature.com/articles/s41467-017-01312-x)

```{r, message=FALSE, results="hide", eval = FALSE}
library(devtools)
install_github("adrientaudiere/lulu")
library("lulu")
data(data_fungi_sp_known)
lulu_res <- lulu_pq(data_fungi_sp_known)
```

```{r, eval = FALSE}
summary_plot_pq(data_fungi_sp_known)
summary_plot_pq(lulu_res$new_physeq)
```
