data("data_fungi")
data("data_fungi_sp_known")
data("GlobalPatterns")
data("enterotype")

data_fungi_low_high <- subset_samples(data_fungi, Height %in% c("Low", "High"))
data_basidio <- subset_taxa(data_fungi, Phylum == "Basidiomycota")
data_fungi_2trees <- subset_samples(data_fungi, data_fungi@sam_data$Tree_name %in% c("A10-005", "AD30-abm-X"))

GlobalPatterns@sam_data[, "Soil_logical"] <- ifelse(GlobalPatterns@sam_data[, "SampleType"] == "Soil", "Soil", "Not Soil")
GP <- subset_samples(GlobalPatterns, GlobalPatterns@sam_data$SampleType %in% c("Soil", "Skin"))
res_deseq <- DESeq2::DESeq(phyloseq_to_deseq2(GP, ~SampleType), test = "Wald", fitType = "local")

test_that("Test one case for each deprecated functions", {
  expect_warning(physeq_graph_test(data_fungi, fact = "Tree_name"), "deprecated")
  expect_s3_class(suppressWarnings(adonis_phyloseq(data_fungi, "Tree_name")), "anova")
  expect_s4_class(suppressWarnings(clean_pq(data_fungi)), "phyloseq")
  expect_s4_class(suppressWarnings(lulu_phyloseq(data_fungi_sp_known)$new_physeq), "phyloseq")
  expect_message(expect_warning(otu_circle(data_fungi_2trees, fact = "Tree_name", nproc = 4, add_nb_seq = FALSE), "deprecated"))
  expect_message(expect_warning(biplot_physeq(data_fungi_2trees, merge_sample_by = "Tree_name"), "deprecated"))

  testFolder <- tempdir()
  unlink(list.files(testFolder, full.names = TRUE), recursive = TRUE)
  expect_warning(write_phyloseq(enterotype, path = testFolder, silent = TRUE), "deprecated")
  expect_s4_class(suppressWarnings(read_phyloseq(testFolder, taxa_are_rows = TRUE)), "phyloseq")

  expect_warning(sankey_phyloseq(data_fungi), "deprecated")
  expect_s3_class(suppressWarnings(summary_plot_phyloseq(data_fungi)), "ggplot")
  expect_message(expect_warning(plot_edgeR_phyloseq(GlobalPatterns, c("SampleType", "Soil", "Feces"), color_tax = "Kingdom"), "deprecated"), "Perform edgeR binary test")
  expect_warning(plot_deseq2_phyloseq(res_deseq, c("SampleType", "Soil", "Skin"), tax_table = GP@tax_table, color_tax = "Kingdom"), "deprecated")
  expect_warning(venn_phyloseq(data_fungi, "Height"), "deprecated")
  expect_warning(ggVenn_phyloseq(data_fungi, "Height"), "deprecated")
  expect_warning(hill_tuckey_phyloseq(GlobalPatterns, "Soil_logical"), "deprecated")
  expect_message(expect_warning(hill_phyloseq(GP, "SampleType"), "deprecated"))
  expect_warning(suppressMessages(ht <- physeq_heat_tree(data_basidio)), "deprecated")
  expect_s3_class(suppressWarnings(multiple_share_bisamples(data_fungi_low_high, bifactor = "Height", merge_sample_by = "Height")), "tbl_df")
})
