test_that("All deprecated functions are ... deprecated", {
  expect_equal(sum(grepl(".Deprecated", getAnywhere(physeq_graph_test))), 1)
  expect_equal(sum(grepl(".Deprecated", getAnywhere(adonis_phyloseq))), 1)
  expect_equal(sum(grepl(".Deprecated", getAnywhere(clean_physeq))), 1)
  expect_equal(sum(grepl(".Deprecated", getAnywhere(lulu_phyloseq))), 1)
  expect_equal(sum(grepl(".Deprecated", getAnywhere(otu_circle))), 1)
  expect_equal(sum(grepl(".Deprecated", getAnywhere(biplot_physeq))), 1)
  expect_equal(sum(grepl(".Deprecated", getAnywhere(read_phyloseq))), 1)
  expect_equal(sum(grepl(".Deprecated", getAnywhere(write_phyloseq))), 1)
  expect_equal(sum(grepl(".Deprecated", getAnywhere(sankey_phyloseq))), 1)
  expect_equal(sum(grepl(".Deprecated", getAnywhere(summary_plot_phyloseq))), 1)
  expect_equal(sum(grepl(".Deprecated", getAnywhere(plot_edgeR_phyloseq))), 1)
  expect_equal(sum(grepl(".Deprecated", getAnywhere(plot_deseq2_phyloseq))), 1)
  expect_equal(sum(grepl(".Deprecated", getAnywhere(venn_phyloseq))), 1)
  expect_equal(sum(grepl(".Deprecated", getAnywhere(ggVenn_phyloseq))), 1)
  expect_equal(sum(grepl(".Deprecated", getAnywhere(hill_tuckey_phyloseq))), 1)
  expect_equal(sum(grepl(".Deprecated", getAnywhere(hill_phyloseq))), 1)
  expect_equal(sum(grepl(".Deprecated", getAnywhere(physeq_heat_tree))), 1)
  expect_equal(sum(grepl(".Deprecated", getAnywhere(multiple_share_bisamples))), 1)
})
