#' \code{MiscMetabar} package
#'
#' Functions to help analyze and visualize metabarcoding data. Mainly based on
#' the phyloseq and dada2 packages.
#' @name MiscMetabar-package
#' @import ggplot2 phyloseq dada2 dplyr purrr
NULL

if (getRversion() >= "2.15.1") {
  utils::globalVariables(c(
    "...1",
    "...2",
    ".group",
    ".id",
    ".stack_order",
    "%>%",
    "Ab",
    "Abundance",
    "aicc",
    "alluvium",
    "alpha_hill",
    "archetype",
    "beta.div",
    "calc_taxon_abund",
    "character_method",
    "chim_rm",
    "Class",
    "clean_fastq",
    "clean_sam",
    "col_tax",
    "color_group",
    "colors",
    "combn",
    "complement",
    "complexity",
    "condition",
    "data_fungi",
    "e-value",
    "edgetype",
    "Family",
    "fill",
    "Genus",
    "grid.draw",
    "grid.layout",
    "group_by",
    "group_id",
    "group",
    "Guild",
    "heat_tree",
    "hill_0",
    "Hill_0",
    "hill_1",
    "Hill_1",
    "hill_2",
    "Hill_2",
    "how name",
    "install_github",
    "install.packages",
    "label_text",
    "label",
    "LCBD",
    "LearnTaxa",
    "log2FoldChange",
    "logFC",
    "LVL1",
    "LVL3",
    "lwr",
    "max_Hill",
    "method",
    "modality",
    "Modality",
    "multcompLetters",
    "na_remove",
    "name",
    "nb_samp",
    "nb_seq",
    "nb_taxa",
    "nb_values",
    "nOTUid",
    "OrientNucleotides",
    "ott_id",
    "OTU",
    "p.adj",
    "p.adjust",
    "pattern_k",
    "physeq",
    "plot_layout value",
    "plot_layout",
    "pos_letters",
    "Proportion",
    "pushViewport",
    "Query name",
    "rarefy",
    "ratio",
    "read.delim",
    "readDNAStringSet",
    "RemoveGaps",
    "reverse",
    "reverseComplement",
    "rgb",
    "rrarefy",
    "Sample_names",
    "Sample",
    "samples_names_common",
    "sampletype",
    "SCBD",
    "seq_id",
    "seq_tab_Pairs",
    "silent",
    "Species",
    "stratum",
    "summarise",
    "tax_col",
    "tax",
    "Taxa name",
    "taxa_fill",
    "taxa_name",
    "taxon_names",
    "taxon",
    "teststat",
    "Time",
    "tnrs_match_names",
    "to_lodes_form",
    "tol_induced_subtree",
    "total",
    "Type",
    "update",
    "upr",
    "upViewport",
    "V1",
    "V2",
    "V3",
    "val",
    "value_bootstrap",
    "value",
    "variable",
    "vegdist",
    "viewport",
    "write.table",
    "x_bar",
    "x_label",
    "x",
    "X1_lim1",
    "X1_lim2",
    "x1",
    "X1",
    "x2",
    "xend",
    "y_bar",
    "y_label",
    "y",
    "y1",
    "y2",
    "yend",
    "ymax",
    "ymid",
    "ymin"
  ))
}

#' @keywords internal
#' @noRd
"_PACKAGE"

## usethis namespace: start
#' @importFrom stats na.exclude na.omit reformulate reorder terms
#' @importFrom lifecycle deprecated
## usethis namespace: end
NULL
